/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DebugEstoqueRouteImport } from './routes/debug-estoque'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrintOperacionalRouteImport } from './routes/print.operacional'
import { Route as PrintIdRouteImport } from './routes/print.$id'
import { Route as AuthenticatedSeparacaoRouteImport } from './routes/_authenticated.separacao'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated.relatorios'
import { Route as AuthenticatedProducaoRouteImport } from './routes/_authenticated.producao'
import { Route as AuthenticatedIaRouteImport } from './routes/_authenticated.ia'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated.financeiro'
import { Route as AuthenticatedExpedicaoRouteImport } from './routes/_authenticated.expedicao'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated.estoque'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated.configuracoes'
import { Route as AuthenticatedBlingCallbackRouteImport } from './routes/_authenticated.bling-callback'
import { Route as AuthenticatedUsuariosIndexRouteImport } from './routes/_authenticated.usuarios.index'
import { Route as AuthenticatedProdutosIndexRouteImport } from './routes/_authenticated.produtos.index'
import { Route as AuthenticatedPedidosIndexRouteImport } from './routes/_authenticated.pedidos.index'
import { Route as AuthenticatedOrcamentosIndexRouteImport } from './routes/_authenticated.orcamentos.index'
import { Route as AuthenticatedFinanceiroIndexRouteImport } from './routes/_authenticated.financeiro.index'
import { Route as AuthenticatedCrmIndexRouteImport } from './routes/_authenticated.crm.index'
import { Route as PrintEtiquetaIdRouteImport } from './routes/print.etiqueta.$id'
import { Route as AuthenticatedUsuariosNovoRouteImport } from './routes/_authenticated.usuarios.novo'
import { Route as AuthenticatedUsuariosIdRouteImport } from './routes/_authenticated.usuarios.$id'
import { Route as AuthenticatedPedidosNovoRouteImport } from './routes/_authenticated.pedidos.novo'
import { Route as AuthenticatedPedidosOrderIdRouteImport } from './routes/_authenticated.pedidos.$orderId'
import { Route as AuthenticatedPedidosIdRouteImport } from './routes/_authenticated.pedidos.$id'
import { Route as AuthenticatedFinanceiroRelatoriosRouteImport } from './routes/_authenticated.financeiro.relatorios'
import { Route as AuthenticatedFinanceiroReceberRouteImport } from './routes/_authenticated.financeiro.receber'
import { Route as AuthenticatedFinanceiroPagarRouteImport } from './routes/_authenticated.financeiro.pagar'
import { Route as AuthenticatedFinanceiroFluxoCaixaRouteImport } from './routes/_authenticated.financeiro.fluxo-caixa'
import { Route as AuthenticatedFinanceiroDreRouteImport } from './routes/_authenticated.financeiro.dre'
import { Route as AuthenticatedFinanceiroConciliacaoRouteImport } from './routes/_authenticated.financeiro.conciliacao'
import { Route as AuthenticatedFinanceiroCentroCustosRouteImport } from './routes/_authenticated.financeiro.centro-custos'
import { Route as AuthenticatedCrmClientIdRouteImport } from './routes/_authenticated.crm.$clientId'
import { Route as AuthenticatedBipagemOrderIdRouteImport } from './routes/_authenticated.bipagem.$orderId'

const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugEstoqueRoute = DebugEstoqueRouteImport.update({
  id: '/debug-estoque',
  path: '/debug-estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintOperacionalRoute = PrintOperacionalRouteImport.update({
  id: '/print/operacional',
  path: '/print/operacional',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintIdRoute = PrintIdRouteImport.update({
  id: '/print/$id',
  path: '/print/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSeparacaoRoute = AuthenticatedSeparacaoRouteImport.update({
  id: '/separacao',
  path: '/separacao',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProducaoRoute = AuthenticatedProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIaRoute = AuthenticatedIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExpedicaoRoute = AuthenticatedExpedicaoRouteImport.update({
  id: '/expedicao',
  path: '/expedicao',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBlingCallbackRoute =
  AuthenticatedBlingCallbackRouteImport.update({
    id: '/bling-callback',
    path: '/bling-callback',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsuariosIndexRoute =
  AuthenticatedUsuariosIndexRouteImport.update({
    id: '/usuarios/',
    path: '/usuarios/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProdutosIndexRoute =
  AuthenticatedProdutosIndexRouteImport.update({
    id: '/produtos/',
    path: '/produtos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPedidosIndexRoute =
  AuthenticatedPedidosIndexRouteImport.update({
    id: '/pedidos/',
    path: '/pedidos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrcamentosIndexRoute =
  AuthenticatedOrcamentosIndexRouteImport.update({
    id: '/orcamentos/',
    path: '/orcamentos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceiroIndexRoute =
  AuthenticatedFinanceiroIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedCrmIndexRoute = AuthenticatedCrmIndexRouteImport.update({
  id: '/crm/',
  path: '/crm/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PrintEtiquetaIdRoute = PrintEtiquetaIdRouteImport.update({
  id: '/print/etiqueta/$id',
  path: '/print/etiqueta/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosNovoRoute =
  AuthenticatedUsuariosNovoRouteImport.update({
    id: '/usuarios/novo',
    path: '/usuarios/novo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsuariosIdRoute = AuthenticatedUsuariosIdRouteImport.update({
  id: '/usuarios/$id',
  path: '/usuarios/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPedidosNovoRoute =
  AuthenticatedPedidosNovoRouteImport.update({
    id: '/pedidos/novo',
    path: '/pedidos/novo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPedidosOrderIdRoute =
  AuthenticatedPedidosOrderIdRouteImport.update({
    id: '/pedidos/$orderId',
    path: '/pedidos/$orderId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPedidosIdRoute = AuthenticatedPedidosIdRouteImport.update({
  id: '/pedidos/$id',
  path: '/pedidos/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceiroRelatoriosRoute =
  AuthenticatedFinanceiroRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedFinanceiroReceberRoute =
  AuthenticatedFinanceiroReceberRouteImport.update({
    id: '/receber',
    path: '/receber',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedFinanceiroPagarRoute =
  AuthenticatedFinanceiroPagarRouteImport.update({
    id: '/pagar',
    path: '/pagar',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedFinanceiroFluxoCaixaRoute =
  AuthenticatedFinanceiroFluxoCaixaRouteImport.update({
    id: '/fluxo-caixa',
    path: '/fluxo-caixa',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedFinanceiroDreRoute =
  AuthenticatedFinanceiroDreRouteImport.update({
    id: '/dre',
    path: '/dre',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedFinanceiroConciliacaoRoute =
  AuthenticatedFinanceiroConciliacaoRouteImport.update({
    id: '/conciliacao',
    path: '/conciliacao',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedFinanceiroCentroCustosRoute =
  AuthenticatedFinanceiroCentroCustosRouteImport.update({
    id: '/centro-custos',
    path: '/centro-custos',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedCrmClientIdRoute =
  AuthenticatedCrmClientIdRouteImport.update({
    id: '/crm/$clientId',
    path: '/crm/$clientId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBipagemOrderIdRoute =
  AuthenticatedBipagemOrderIdRouteImport.update({
    id: '/bipagem/$orderId',
    path: '/bipagem/$orderId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/debug-estoque': typeof DebugEstoqueRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/bling-callback': typeof AuthenticatedBlingCallbackRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/expedicao': typeof AuthenticatedExpedicaoRoute
  '/financeiro': typeof AuthenticatedFinanceiroRouteWithChildren
  '/ia': typeof AuthenticatedIaRoute
  '/producao': typeof AuthenticatedProducaoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/separacao': typeof AuthenticatedSeparacaoRoute
  '/print/$id': typeof PrintIdRoute
  '/print/operacional': typeof PrintOperacionalRoute
  '/bipagem/$orderId': typeof AuthenticatedBipagemOrderIdRoute
  '/crm/$clientId': typeof AuthenticatedCrmClientIdRoute
  '/financeiro/centro-custos': typeof AuthenticatedFinanceiroCentroCustosRoute
  '/financeiro/conciliacao': typeof AuthenticatedFinanceiroConciliacaoRoute
  '/financeiro/dre': typeof AuthenticatedFinanceiroDreRoute
  '/financeiro/fluxo-caixa': typeof AuthenticatedFinanceiroFluxoCaixaRoute
  '/financeiro/pagar': typeof AuthenticatedFinanceiroPagarRoute
  '/financeiro/receber': typeof AuthenticatedFinanceiroReceberRoute
  '/financeiro/relatorios': typeof AuthenticatedFinanceiroRelatoriosRoute
  '/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/pedidos/$orderId': typeof AuthenticatedPedidosOrderIdRoute
  '/pedidos/novo': typeof AuthenticatedPedidosNovoRoute
  '/usuarios/$id': typeof AuthenticatedUsuariosIdRoute
  '/usuarios/novo': typeof AuthenticatedUsuariosNovoRoute
  '/print/etiqueta/$id': typeof PrintEtiquetaIdRoute
  '/crm/': typeof AuthenticatedCrmIndexRoute
  '/financeiro/': typeof AuthenticatedFinanceiroIndexRoute
  '/orcamentos/': typeof AuthenticatedOrcamentosIndexRoute
  '/pedidos/': typeof AuthenticatedPedidosIndexRoute
  '/produtos/': typeof AuthenticatedProdutosIndexRoute
  '/usuarios/': typeof AuthenticatedUsuariosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/debug-estoque': typeof DebugEstoqueRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/bling-callback': typeof AuthenticatedBlingCallbackRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/expedicao': typeof AuthenticatedExpedicaoRoute
  '/ia': typeof AuthenticatedIaRoute
  '/producao': typeof AuthenticatedProducaoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/separacao': typeof AuthenticatedSeparacaoRoute
  '/print/$id': typeof PrintIdRoute
  '/print/operacional': typeof PrintOperacionalRoute
  '/bipagem/$orderId': typeof AuthenticatedBipagemOrderIdRoute
  '/crm/$clientId': typeof AuthenticatedCrmClientIdRoute
  '/financeiro/centro-custos': typeof AuthenticatedFinanceiroCentroCustosRoute
  '/financeiro/conciliacao': typeof AuthenticatedFinanceiroConciliacaoRoute
  '/financeiro/dre': typeof AuthenticatedFinanceiroDreRoute
  '/financeiro/fluxo-caixa': typeof AuthenticatedFinanceiroFluxoCaixaRoute
  '/financeiro/pagar': typeof AuthenticatedFinanceiroPagarRoute
  '/financeiro/receber': typeof AuthenticatedFinanceiroReceberRoute
  '/financeiro/relatorios': typeof AuthenticatedFinanceiroRelatoriosRoute
  '/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/pedidos/$orderId': typeof AuthenticatedPedidosOrderIdRoute
  '/pedidos/novo': typeof AuthenticatedPedidosNovoRoute
  '/usuarios/$id': typeof AuthenticatedUsuariosIdRoute
  '/usuarios/novo': typeof AuthenticatedUsuariosNovoRoute
  '/print/etiqueta/$id': typeof PrintEtiquetaIdRoute
  '/crm': typeof AuthenticatedCrmIndexRoute
  '/financeiro': typeof AuthenticatedFinanceiroIndexRoute
  '/orcamentos': typeof AuthenticatedOrcamentosIndexRoute
  '/pedidos': typeof AuthenticatedPedidosIndexRoute
  '/produtos': typeof AuthenticatedProdutosIndexRoute
  '/usuarios': typeof AuthenticatedUsuariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/debug-estoque': typeof DebugEstoqueRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/_authenticated/bling-callback': typeof AuthenticatedBlingCallbackRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRoute
  '/_authenticated/expedicao': typeof AuthenticatedExpedicaoRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRouteWithChildren
  '/_authenticated/ia': typeof AuthenticatedIaRoute
  '/_authenticated/producao': typeof AuthenticatedProducaoRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/separacao': typeof AuthenticatedSeparacaoRoute
  '/print/$id': typeof PrintIdRoute
  '/print/operacional': typeof PrintOperacionalRoute
  '/_authenticated/bipagem/$orderId': typeof AuthenticatedBipagemOrderIdRoute
  '/_authenticated/crm/$clientId': typeof AuthenticatedCrmClientIdRoute
  '/_authenticated/financeiro/centro-custos': typeof AuthenticatedFinanceiroCentroCustosRoute
  '/_authenticated/financeiro/conciliacao': typeof AuthenticatedFinanceiroConciliacaoRoute
  '/_authenticated/financeiro/dre': typeof AuthenticatedFinanceiroDreRoute
  '/_authenticated/financeiro/fluxo-caixa': typeof AuthenticatedFinanceiroFluxoCaixaRoute
  '/_authenticated/financeiro/pagar': typeof AuthenticatedFinanceiroPagarRoute
  '/_authenticated/financeiro/receber': typeof AuthenticatedFinanceiroReceberRoute
  '/_authenticated/financeiro/relatorios': typeof AuthenticatedFinanceiroRelatoriosRoute
  '/_authenticated/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/_authenticated/pedidos/$orderId': typeof AuthenticatedPedidosOrderIdRoute
  '/_authenticated/pedidos/novo': typeof AuthenticatedPedidosNovoRoute
  '/_authenticated/usuarios/$id': typeof AuthenticatedUsuariosIdRoute
  '/_authenticated/usuarios/novo': typeof AuthenticatedUsuariosNovoRoute
  '/print/etiqueta/$id': typeof PrintEtiquetaIdRoute
  '/_authenticated/crm/': typeof AuthenticatedCrmIndexRoute
  '/_authenticated/financeiro/': typeof AuthenticatedFinanceiroIndexRoute
  '/_authenticated/orcamentos/': typeof AuthenticatedOrcamentosIndexRoute
  '/_authenticated/pedidos/': typeof AuthenticatedPedidosIndexRoute
  '/_authenticated/produtos/': typeof AuthenticatedProdutosIndexRoute
  '/_authenticated/usuarios/': typeof AuthenticatedUsuariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/debug-estoque'
    | '/login'
    | '/redefinir-senha'
    | '/bling-callback'
    | '/configuracoes'
    | '/dashboard'
    | '/estoque'
    | '/expedicao'
    | '/financeiro'
    | '/ia'
    | '/producao'
    | '/relatorios'
    | '/separacao'
    | '/print/$id'
    | '/print/operacional'
    | '/bipagem/$orderId'
    | '/crm/$clientId'
    | '/financeiro/centro-custos'
    | '/financeiro/conciliacao'
    | '/financeiro/dre'
    | '/financeiro/fluxo-caixa'
    | '/financeiro/pagar'
    | '/financeiro/receber'
    | '/financeiro/relatorios'
    | '/pedidos/$id'
    | '/pedidos/$orderId'
    | '/pedidos/novo'
    | '/usuarios/$id'
    | '/usuarios/novo'
    | '/print/etiqueta/$id'
    | '/crm/'
    | '/financeiro/'
    | '/orcamentos/'
    | '/pedidos/'
    | '/produtos/'
    | '/usuarios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/debug-estoque'
    | '/login'
    | '/redefinir-senha'
    | '/bling-callback'
    | '/configuracoes'
    | '/dashboard'
    | '/estoque'
    | '/expedicao'
    | '/ia'
    | '/producao'
    | '/relatorios'
    | '/separacao'
    | '/print/$id'
    | '/print/operacional'
    | '/bipagem/$orderId'
    | '/crm/$clientId'
    | '/financeiro/centro-custos'
    | '/financeiro/conciliacao'
    | '/financeiro/dre'
    | '/financeiro/fluxo-caixa'
    | '/financeiro/pagar'
    | '/financeiro/receber'
    | '/financeiro/relatorios'
    | '/pedidos/$id'
    | '/pedidos/$orderId'
    | '/pedidos/novo'
    | '/usuarios/$id'
    | '/usuarios/novo'
    | '/print/etiqueta/$id'
    | '/crm'
    | '/financeiro'
    | '/orcamentos'
    | '/pedidos'
    | '/produtos'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/debug-estoque'
    | '/login'
    | '/redefinir-senha'
    | '/_authenticated/bling-callback'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/estoque'
    | '/_authenticated/expedicao'
    | '/_authenticated/financeiro'
    | '/_authenticated/ia'
    | '/_authenticated/producao'
    | '/_authenticated/relatorios'
    | '/_authenticated/separacao'
    | '/print/$id'
    | '/print/operacional'
    | '/_authenticated/bipagem/$orderId'
    | '/_authenticated/crm/$clientId'
    | '/_authenticated/financeiro/centro-custos'
    | '/_authenticated/financeiro/conciliacao'
    | '/_authenticated/financeiro/dre'
    | '/_authenticated/financeiro/fluxo-caixa'
    | '/_authenticated/financeiro/pagar'
    | '/_authenticated/financeiro/receber'
    | '/_authenticated/financeiro/relatorios'
    | '/_authenticated/pedidos/$id'
    | '/_authenticated/pedidos/$orderId'
    | '/_authenticated/pedidos/novo'
    | '/_authenticated/usuarios/$id'
    | '/_authenticated/usuarios/novo'
    | '/print/etiqueta/$id'
    | '/_authenticated/crm/'
    | '/_authenticated/financeiro/'
    | '/_authenticated/orcamentos/'
    | '/_authenticated/pedidos/'
    | '/_authenticated/produtos/'
    | '/_authenticated/usuarios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DebugEstoqueRoute: typeof DebugEstoqueRoute
  LoginRoute: typeof LoginRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  PrintIdRoute: typeof PrintIdRoute
  PrintOperacionalRoute: typeof PrintOperacionalRoute
  PrintEtiquetaIdRoute: typeof PrintEtiquetaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug-estoque': {
      id: '/debug-estoque'
      path: '/debug-estoque'
      fullPath: '/debug-estoque'
      preLoaderRoute: typeof DebugEstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/operacional': {
      id: '/print/operacional'
      path: '/print/operacional'
      fullPath: '/print/operacional'
      preLoaderRoute: typeof PrintOperacionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/$id': {
      id: '/print/$id'
      path: '/print/$id'
      fullPath: '/print/$id'
      preLoaderRoute: typeof PrintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/separacao': {
      id: '/_authenticated/separacao'
      path: '/separacao'
      fullPath: '/separacao'
      preLoaderRoute: typeof AuthenticatedSeparacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/producao': {
      id: '/_authenticated/producao'
      path: '/producao'
      fullPath: '/producao'
      preLoaderRoute: typeof AuthenticatedProducaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ia': {
      id: '/_authenticated/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof AuthenticatedIaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expedicao': {
      id: '/_authenticated/expedicao'
      path: '/expedicao'
      fullPath: '/expedicao'
      preLoaderRoute: typeof AuthenticatedExpedicaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bling-callback': {
      id: '/_authenticated/bling-callback'
      path: '/bling-callback'
      fullPath: '/bling-callback'
      preLoaderRoute: typeof AuthenticatedBlingCallbackRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/usuarios/': {
      id: '/_authenticated/usuarios/'
      path: '/usuarios'
      fullPath: '/usuarios/'
      preLoaderRoute: typeof AuthenticatedUsuariosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/produtos/': {
      id: '/_authenticated/produtos/'
      path: '/produtos'
      fullPath: '/produtos/'
      preLoaderRoute: typeof AuthenticatedProdutosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pedidos/': {
      id: '/_authenticated/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof AuthenticatedPedidosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orcamentos/': {
      id: '/_authenticated/orcamentos/'
      path: '/orcamentos'
      fullPath: '/orcamentos/'
      preLoaderRoute: typeof AuthenticatedOrcamentosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro/': {
      id: '/_authenticated/financeiro/'
      path: '/'
      fullPath: '/financeiro/'
      preLoaderRoute: typeof AuthenticatedFinanceiroIndexRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/crm/': {
      id: '/_authenticated/crm/'
      path: '/crm'
      fullPath: '/crm/'
      preLoaderRoute: typeof AuthenticatedCrmIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/print/etiqueta/$id': {
      id: '/print/etiqueta/$id'
      path: '/print/etiqueta/$id'
      fullPath: '/print/etiqueta/$id'
      preLoaderRoute: typeof PrintEtiquetaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios/novo': {
      id: '/_authenticated/usuarios/novo'
      path: '/usuarios/novo'
      fullPath: '/usuarios/novo'
      preLoaderRoute: typeof AuthenticatedUsuariosNovoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/usuarios/$id': {
      id: '/_authenticated/usuarios/$id'
      path: '/usuarios/$id'
      fullPath: '/usuarios/$id'
      preLoaderRoute: typeof AuthenticatedUsuariosIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pedidos/novo': {
      id: '/_authenticated/pedidos/novo'
      path: '/pedidos/novo'
      fullPath: '/pedidos/novo'
      preLoaderRoute: typeof AuthenticatedPedidosNovoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pedidos/$orderId': {
      id: '/_authenticated/pedidos/$orderId'
      path: '/pedidos/$orderId'
      fullPath: '/pedidos/$orderId'
      preLoaderRoute: typeof AuthenticatedPedidosOrderIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pedidos/$id': {
      id: '/_authenticated/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/pedidos/$id'
      preLoaderRoute: typeof AuthenticatedPedidosIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro/relatorios': {
      id: '/_authenticated/financeiro/relatorios'
      path: '/relatorios'
      fullPath: '/financeiro/relatorios'
      preLoaderRoute: typeof AuthenticatedFinanceiroRelatoriosRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/financeiro/receber': {
      id: '/_authenticated/financeiro/receber'
      path: '/receber'
      fullPath: '/financeiro/receber'
      preLoaderRoute: typeof AuthenticatedFinanceiroReceberRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/financeiro/pagar': {
      id: '/_authenticated/financeiro/pagar'
      path: '/pagar'
      fullPath: '/financeiro/pagar'
      preLoaderRoute: typeof AuthenticatedFinanceiroPagarRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/financeiro/fluxo-caixa': {
      id: '/_authenticated/financeiro/fluxo-caixa'
      path: '/fluxo-caixa'
      fullPath: '/financeiro/fluxo-caixa'
      preLoaderRoute: typeof AuthenticatedFinanceiroFluxoCaixaRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/financeiro/dre': {
      id: '/_authenticated/financeiro/dre'
      path: '/dre'
      fullPath: '/financeiro/dre'
      preLoaderRoute: typeof AuthenticatedFinanceiroDreRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/financeiro/conciliacao': {
      id: '/_authenticated/financeiro/conciliacao'
      path: '/conciliacao'
      fullPath: '/financeiro/conciliacao'
      preLoaderRoute: typeof AuthenticatedFinanceiroConciliacaoRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/financeiro/centro-custos': {
      id: '/_authenticated/financeiro/centro-custos'
      path: '/centro-custos'
      fullPath: '/financeiro/centro-custos'
      preLoaderRoute: typeof AuthenticatedFinanceiroCentroCustosRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/crm/$clientId': {
      id: '/_authenticated/crm/$clientId'
      path: '/crm/$clientId'
      fullPath: '/crm/$clientId'
      preLoaderRoute: typeof AuthenticatedCrmClientIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bipagem/$orderId': {
      id: '/_authenticated/bipagem/$orderId'
      path: '/bipagem/$orderId'
      fullPath: '/bipagem/$orderId'
      preLoaderRoute: typeof AuthenticatedBipagemOrderIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedFinanceiroRouteChildren {
  AuthenticatedFinanceiroCentroCustosRoute: typeof AuthenticatedFinanceiroCentroCustosRoute
  AuthenticatedFinanceiroConciliacaoRoute: typeof AuthenticatedFinanceiroConciliacaoRoute
  AuthenticatedFinanceiroDreRoute: typeof AuthenticatedFinanceiroDreRoute
  AuthenticatedFinanceiroFluxoCaixaRoute: typeof AuthenticatedFinanceiroFluxoCaixaRoute
  AuthenticatedFinanceiroPagarRoute: typeof AuthenticatedFinanceiroPagarRoute
  AuthenticatedFinanceiroReceberRoute: typeof AuthenticatedFinanceiroReceberRoute
  AuthenticatedFinanceiroRelatoriosRoute: typeof AuthenticatedFinanceiroRelatoriosRoute
  AuthenticatedFinanceiroIndexRoute: typeof AuthenticatedFinanceiroIndexRoute
}

const AuthenticatedFinanceiroRouteChildren: AuthenticatedFinanceiroRouteChildren =
  {
    AuthenticatedFinanceiroCentroCustosRoute:
      AuthenticatedFinanceiroCentroCustosRoute,
    AuthenticatedFinanceiroConciliacaoRoute:
      AuthenticatedFinanceiroConciliacaoRoute,
    AuthenticatedFinanceiroDreRoute: AuthenticatedFinanceiroDreRoute,
    AuthenticatedFinanceiroFluxoCaixaRoute:
      AuthenticatedFinanceiroFluxoCaixaRoute,
    AuthenticatedFinanceiroPagarRoute: AuthenticatedFinanceiroPagarRoute,
    AuthenticatedFinanceiroReceberRoute: AuthenticatedFinanceiroReceberRoute,
    AuthenticatedFinanceiroRelatoriosRoute:
      AuthenticatedFinanceiroRelatoriosRoute,
    AuthenticatedFinanceiroIndexRoute: AuthenticatedFinanceiroIndexRoute,
  }

const AuthenticatedFinanceiroRouteWithChildren =
  AuthenticatedFinanceiroRoute._addFileChildren(
    AuthenticatedFinanceiroRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedBlingCallbackRoute: typeof AuthenticatedBlingCallbackRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRoute
  AuthenticatedExpedicaoRoute: typeof AuthenticatedExpedicaoRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRouteWithChildren
  AuthenticatedIaRoute: typeof AuthenticatedIaRoute
  AuthenticatedProducaoRoute: typeof AuthenticatedProducaoRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedSeparacaoRoute: typeof AuthenticatedSeparacaoRoute
  AuthenticatedBipagemOrderIdRoute: typeof AuthenticatedBipagemOrderIdRoute
  AuthenticatedCrmClientIdRoute: typeof AuthenticatedCrmClientIdRoute
  AuthenticatedPedidosIdRoute: typeof AuthenticatedPedidosIdRoute
  AuthenticatedPedidosOrderIdRoute: typeof AuthenticatedPedidosOrderIdRoute
  AuthenticatedPedidosNovoRoute: typeof AuthenticatedPedidosNovoRoute
  AuthenticatedUsuariosIdRoute: typeof AuthenticatedUsuariosIdRoute
  AuthenticatedUsuariosNovoRoute: typeof AuthenticatedUsuariosNovoRoute
  AuthenticatedCrmIndexRoute: typeof AuthenticatedCrmIndexRoute
  AuthenticatedOrcamentosIndexRoute: typeof AuthenticatedOrcamentosIndexRoute
  AuthenticatedPedidosIndexRoute: typeof AuthenticatedPedidosIndexRoute
  AuthenticatedProdutosIndexRoute: typeof AuthenticatedProdutosIndexRoute
  AuthenticatedUsuariosIndexRoute: typeof AuthenticatedUsuariosIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBlingCallbackRoute: AuthenticatedBlingCallbackRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRoute,
  AuthenticatedExpedicaoRoute: AuthenticatedExpedicaoRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRouteWithChildren,
  AuthenticatedIaRoute: AuthenticatedIaRoute,
  AuthenticatedProducaoRoute: AuthenticatedProducaoRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedSeparacaoRoute: AuthenticatedSeparacaoRoute,
  AuthenticatedBipagemOrderIdRoute: AuthenticatedBipagemOrderIdRoute,
  AuthenticatedCrmClientIdRoute: AuthenticatedCrmClientIdRoute,
  AuthenticatedPedidosIdRoute: AuthenticatedPedidosIdRoute,
  AuthenticatedPedidosOrderIdRoute: AuthenticatedPedidosOrderIdRoute,
  AuthenticatedPedidosNovoRoute: AuthenticatedPedidosNovoRoute,
  AuthenticatedUsuariosIdRoute: AuthenticatedUsuariosIdRoute,
  AuthenticatedUsuariosNovoRoute: AuthenticatedUsuariosNovoRoute,
  AuthenticatedCrmIndexRoute: AuthenticatedCrmIndexRoute,
  AuthenticatedOrcamentosIndexRoute: AuthenticatedOrcamentosIndexRoute,
  AuthenticatedPedidosIndexRoute: AuthenticatedPedidosIndexRoute,
  AuthenticatedProdutosIndexRoute: AuthenticatedProdutosIndexRoute,
  AuthenticatedUsuariosIndexRoute: AuthenticatedUsuariosIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DebugEstoqueRoute: DebugEstoqueRoute,
  LoginRoute: LoginRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  PrintIdRoute: PrintIdRoute,
  PrintOperacionalRoute: PrintOperacionalRoute,
  PrintEtiquetaIdRoute: PrintEtiquetaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
